# Generated by Django 4.1.7 on 2023-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='media')),
                ('comment', models.TextField()),
            ],
        ),
    ]
